name: AywenCraftPlugin
version: '${version}'
main: fr.communaywen.core.AywenCraftPlugin
api-version: '1.20'
depend:
  - ProtocolLib

permissions:
  ayw.admin.version:
    description: Permission pour utiliser la commande /version
    default: op
  ayw.command.manuallink:
    description: Permission de lier un deux comptes manuellement
    default: op
  ayw.command.prout:
    description: 'Prout !'
    default: true
  ayw.command.teams:
    description: 'Teams'
    default: true
  ayw.command.rules:
    description: 'Rules'
    default: true
  ayw.command.rtp:
    description: 'rtp'
    default: true
  ayw.command.feed:
    description: 'feed'
    default: true
  ayw.command.tpa:
    description: 'tpa'
    default: true
  openmc.staff.freeze:
    description: 'freeze'
    default: false
  openmc.command.fboom:
    description: 'Créer une explosion de falling blocks autour du joueur'
    default: op

  openmc.staff.players:
    description: 'players'
    default: false
  aywencraft.antivpn.notification:
    description: 'Permission to receive VPN connection notifications'
    default: op
  aywencraft.antivpn.bypass:
    description: 'Permission to bypass VPN check'
    default: false
  ayw.command.spawn:
    description: 'spawn'
    default: true
